### ISSUE TITLE
User and config settings should go in same object

### ISSUE THREAD

**Issue by fitnr** [fitnr/twitter_bot_utils#1]
With user settings overriding global.

``` yaml
users:
    account:
        foo: bar
        breakfast: spam

foo: baz
brunch: eggs
```

``` python
api = api.API('account')

api.config.foo
# bar

api.config.brunch
# eggs
```

For "simplicity", create a new config class to handle this junk?
